repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
    - id: mypy
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=4096']
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: trailing-whitespace
